name: Build CI

# Trigger the workflow on push or pull request
on: [push]

jobs:
  build:
    name: Build

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Build Plugin Source
        run: cd src && npm i && npm i -g typescript && tsc

      - name: Lint
        run: cd src && npm run tslint

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install PIP
        run: |
          sudo pip install --upgrade pip
          sudo pip install six

      - name: Setup NativeScript CLI
        run: |
          echo no | npm i -g nativescript
          tns usage-reporting disable
          tns error-reporting disable

      - name: Build Android Demo App
        run: |
          cd demo
          tns build android --env.uglify
          tns build ios --env.uglify
